plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'org.acoustixaudio.opiqo.multi'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "org.acoustixaudio.opiqo.multi"
        minSdk 34
        targetSdk 36
        versionCode 5
        versionName '0.97'

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ''
                arguments "-DANDROID_STL=c++_shared"
            }
        }

        ndk {
            debugSymbolLevel 'FULL' // or 'FULL'
        }
        versionNameSuffix '-Jag-Stang'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            ndk {
                debugSymbolLevel 'FULL' // or 'FULL'
            }
        }

        debug {
            // Retains full debug symbols in the .so file
            ndk {
                debugSymbolLevel 'FULL' // or 'FULL'
            }

        }

    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    buildFeatures {
        prefab true
    }

}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.preference
    testImplementation libs.junit
    implementation 'com.google.oboe:oboe:1.10.0'
    implementation libs.billing

    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}